### ISSUE TITLE
[BUG] rho stats temp output treecorr file

### ISSUE THREAD

**Issue by martinkilbinger** [CosmoStat/shapepipe#621]
**Describe the bug**
mccd_plot_runner ends with an error when computing the rho statistics under mode == HSC.

Here is a log output, using input from shaepipe v1:

04/04/2023 15:48:12  > Computing rho statistics...
04/04/2023 15:48:12 ERROR: Cannot use given fields: ["{'coords':", "'spherical',", "'metric':", "'Euclidean',", "'sep_units':", "'arcmin',", "'bin_type':", "'Log'}"]
Traceback (most recent call last):
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/pipeline/worker_handler.py", line 180, in _run_worker
    with_timeout(self.worker_dict['timeout'], self.w_log.name)(
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/pipeline/timeout.py", line 42, in inner
    return decorated(*args, **kwargs)
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/pipeline/worker_handler.py", line 194, in _worker_execution
    self._run_module()
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/pipeline/worker_handler.py", line 215, in _run_module
    self._stdout, self._stderr = self._module_runner(
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/modules/mccd_plots_runner.py", line 140, in mccd_plots_runner
    mccd_plots.rho_stats(
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/modules/mccd_package/mccd_plot_utilities.py", line 1508, in rho_stats
    rho_results = [
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/shapepipe/modules/mccd_package/mccd_plot_utilities.py", line 1509, in <listcomp>
    rho_stat(stilecat, config=TreeCorrConfig)
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/stile/sys_tests.py", line 819, in __call__
    return self.getCF('gg', new_data, new_data2, new_random, new_random2,
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/stile/sys_tests.py", line 543, in getCF
    results = stile.ReadTreeCorrResultsFile(output_file)
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/stile/treecorr_utils.py", line 105, in ReadTreeCorrResultsFile
    return stile_utils.FormatArray(output, fields=fields)
  File "/home/mkilbing/.conda/envs/shapepipe/lib/python3.9/site-packages/stile/stile_utils.py", line 90, in FormatArray
    raise RuntimeError('Cannot use given fields: '+str(fields))
RuntimeError: Cannot use given fields: ["{'coords':", "'spherical',", "'metric':", "'Euclidean',", "'sep_units':", "'arcmin',", "'bin_type':", "'Log'}"]
04/04/2023 15:48:12 The log file has been closed.

Check whether this error persists under the newest version.

**Comment by martinkilbinger** [comment]
Close, this is due to version imcompabilities between stile and treecorr. Should be resolved when using correct versions in conda env.
